plugins { id 'com.android.application' }
android {
    namespace 'com.explapp.badrlegacy'
    compileSdk 33
    defaultConfig {
        applicationId 'com.explapp.badrlegacy'
        minSdk 19
        targetSdk 28
        versionCode 6
        versionName '3.2.0-legacy'
    }
    buildTypes { release { minifyEnabled false } }
    lintOptions { abortOnError true; disable 'ExpiredTargetSdkVersion' }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
