plugins { id 'com.android.application' }
android {
    namespace 'com.explapp.badrlegacy'
    compileSdk 33
    defaultConfig {
        applicationId 'com.explapp.badrlegacy'
        minSdk 19
        targetSdk 28
        versionCode 3
        versionName '2.1.0-legacy'
    }
    buildTypes { release { minifyEnabled false } }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
